[features]
seeds = false
skip-lint = false
[programs.localnet]
private-voting = "8SmFN6YA4VBf3SKtYeB9oDcffdbukRKakBp5JYcnqtEc"
verifiable-data-registry = "4SwFwwPrYGRbctsxaK3iuLCdhPyRJy6cUVbe6GK1zSDr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vinh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
